In [12]:
import numpy as np

x = np.array([[1,2], [3,4],[5,6]])
y = x[[0,1,2], [0,1,0]]

print(x)
print(y)

print(x[[0,1,2,2,1,1]])

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[[1 2]
 [3 4]
 [5 6]
 [5 6]
 [3 4]
 [3 4]]


In [17]:
x1 = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x1)

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
print(rows)
print(cols)
print(x1[rows, cols])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 0]
 [3 3]]
[[0 2]
 [0 2]]
[[ 0  2]
 [ 9 11]]


In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

b = a[1:3, 1:3]
print(b)

c = a[1:3,[1,2]]
print(c)

d = a[...,1:]
print(d)

[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [25]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)

print(x[x <= 5])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2 3 4 5]


In [27]:
a = np.array([np.nan, 1, 2, np.nan, 3, 4,5])
print(a[~np.isnan(a)])
print(a[np.isnan(a)])

[1. 2. 3. 4. 5.]
[nan nan]


In [30]:
x = np.arange(9)
print(x)

x2 = x[[0,6]]
print(x2)

[0 1 2 3 4 5 6 7 8]
[0 6]


In [34]:
x = np.arange(32).reshape(8,4)
print(x)
print("\n")
print(x[[1,5,7,2]])
print("\n")
print(x[[0,3,1,2]])
print("\n")
print("x array")
print(x[[1,5,7,2],[0,3,1,2]])
print("\n")
print(x[np.ix_([1,5,7,2],[0,3,1,2])])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]


[[ 0  1  2  3]
 [12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]]


x array
[ 4 23 29 10]


[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [44]:
b = np.array([1,2,3])
print(np.tile(b, (2,1)))

[[1 2 3]
 [1 2 3]]


In [54]:
a = np.arange(8).reshape(2,2,2)
print(a)
# print(np.where(a==6))
# print(a[np.where(a==6)])
b = np.rollaxis(a, 2, 1)
print(b)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


In [61]:
a = [i for i in range(100) if i % 2 != 0 and i >= 11]
print(a)
b = [i for i in range(102) if i %2 != 0 and i >= 13]
print(b)

print(np.sum(np.multiply(a, b)))

[11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]
[13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101]
171435


In [64]:
x = [i for i in range(100) if i % 2 == 0 and i >= 10]
print(x)
print(sum(x))
print(450+2*22*45)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]
2430
2430


In [ ]:
def createnum(a, b, l):
    n = [a,b]
    while True:
        if len(n) == l:
            break
        s = str(n[-1]+n[-2])
        for j in range(len(s)):
            n.append(int(s[j]))

    return n
num = createnum(9,6,2019)

print(len(num))    
print(sum(num))
print(num)