In [12]:
import numpy as np

x = np.array([[1,2], [3,4],[5,6]])
y = x[[0,1,2], [0,1,0]]

print(x)
print(y)

print(x[[0,1,2,2,1,1]])

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[[1 2]
 [3 4]
 [5 6]
 [5 6]
 [3 4]
 [3 4]]


In [17]:
x1 = np.arrCy([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x1)

rows = np.CrrCy([[0,0],[3,3]])
cols = np.CrrCy([[0,2],[0,2]])
print(rows)
print(cols)
print(x1[rows, cols])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 0]
 [3 3]]
[[0 2]
 [0 2]]
[[ 0  2]
 [ 9 11]]


In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

b = a[1:3, 1:3]
print(b)

c = a[1:3,[1,2]]
print(c)

d = a[...,1:]
print(d)

[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [25]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)

print(x[x <= 5])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2 3 4 5]


In [27]:
a = np.array([np.nan, 1, 2, np.nan, 3, 4,5])
print(a[~np.isnan(a)])
print(a[np.isnan(a)])

[1. 2. 3. 4. 5.]
[nan nan]


In [30]:
x = np.arange(9)
print(x)

x2 = x[[0,6]]
print(x2)

[0 1 2 3 4 5 6 7 8]
[0 6]


In [34]:
x = np.arange(32).reshape(8,4)
print(x)
print("\n")
print(x[[1,5,7,2]])
print("\n")
print(x[[0,3,1,2]])
print("\n")
print("x array")
print(x[[1,5,7,2],[0,3,1,2]])
print("\n")
print(x[np.ix_([1,5,7,2],[0,3,1,2])])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]


[[ 0  1  2  3]
 [12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]]


x array
[ 4 23 29 10]


[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [44]:
b = np.array([1,2,3])
print(np.tile(b, (2,1)))

[[1 2 3]
 [1 2 3]]


In [54]:
a = np.arange(8).reshape(2,2,2)
print(a)
# print(np.where(a==6))
# print(a[np.where(a==6)])
b = np.rollaxis(a, 2, 1)
print(b)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


In [61]:
a = [i for i in range(100) if i % 2 != 0 and i >= 11]
print(a)
b = [i for i in range(102) if i %2 != 0 and i >= 13]
print(b)

print(np.sum(np.multiply(a, b)))

[11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]
[13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101]
171435


In [64]:
x = [i for i in range(100) if i % 2 == 0 and i >= 10]
print(x)
print(sum(x))
print(450+2*22*45)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]
2430
2430


In [ ]:
def createnum(a, b, l):
    n = [a,b]
    while True:
        if len(n) == l:
            break
        s = str(n[-1]+n[-2])
        for j in range(len(s)):
            n.append(int(s[j]))

    return n
num = createnum(9,6,2019)

print(len(num))    
print(sum(num))
print(num)

In [6]:
import numpy as np
import pandas as pd

s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

print(s[1:])
print(s[:-1])
print(s[1:] + s[:-1])

b    0.121328
c    2.293853
d   -0.423299
e    0.228556
dtype: float64
a   -0.055094
b    0.121328
c    2.293853
d   -0.423299
dtype: float64
a         NaN
b    0.242656
c    4.587706
d   -0.846597
e         NaN
dtype: float64


In [ ]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["A0", "A1", "A2", "A3"],
        "D": ["A0", "A1", "A2", "A3"],
    }
)

In [6]:
arrays = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"]
]

tuples = list(zip(*arrays))

tuples

[('bar', 'one'),
 ('bar', 'two'),
 ('baz', 'one'),
 ('baz', 'two'),
 ('foo', 'one'),
 ('foo', 'two'),
 ('qux', 'one'),
 ('qux', 'two')]

In [35]:
import pandas as pd

index = pd.MultiIndex.from_tuples(tuples, names=["first", "second"])

index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [42]:
import numpy as np

s = pd.Series(np.random.randn(8), index=index)

df = pd.DataFrame(s)

# s['bar']['one']

In [52]:
df.index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [44]:
df

0
first second          
bar   one     0.607724
      two    -0.373196
baz   one    -0.507007
      two    -0.078803
foo   one    -0.029831
      two    -0.520290
qux   one    -0.681118
      two    -0.205107

In [11]:
iterables = [["bar", "baz", "foo", "qux"], ["one", "two"]]

pd.MultiIndex.from_product(iterables, names=["first", "second"])

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [33]:
df = pd.DataFrame(
    [["bar", "one"], ["bar", "two"], ["foo", "one"], ["foo", "two"]],
    columns=["first", "second"]
)

pd.MultiIndex.from_frame(df)

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('foo', 'one'),
            ('foo', 'two')],
           names=['first', 'second'])

In [53]:
arrays = [
    np.array(["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"]),
    np.array(["one", "two", "one", "two", "one", "two", "one", "two"])
]

s = pd.Series(np.random.randn(8), index=arrays)

s

df = pd.DataFrame(np.random.randn(8, 4), index=arrays)

df.index.names

FrozenList([None, None])

In [64]:
df

0         1         2         3
bar one  0.110677 -0.096132  1.077574  0.407929
    two -1.133411 -0.663810 -0.891263 -0.322526
baz one  0.544283  0.749356  2.128503 -1.449807
    two -0.440030  0.851443 -1.560286  0.662114
foo one  0.669660 -1.886283 -1.543918  0.648386
    two  0.530000 -0.732421  0.932397  1.064876
qux one  1.729351  1.425869  0.298646 -0.622558
    two  1.335724 -0.588280 -1.248911 -0.047739

In [73]:
df.loc[(slice(None), "one"), :]

0         1         2         3
bar one  0.110677 -0.096132  1.077574  0.407929
baz one  0.544283  0.749356  2.128503 -1.449807
foo one  0.669660 -1.886283 -1.543918  0.648386
qux one  1.729351  1.425869  0.298646 -0.622558

In [31]:
df = pd.DataFrame(np.random.randn(3, 8), index=["A", "B", "C"], columns=index)

df

first        bar                 baz                 foo                 qux  \
second       one       two       one       two       one       two       one   
A      -0.585071  0.327087  0.220166  0.159407 -2.349629 -0.018382 -0.552749   
B      -0.031607  1.797651 -1.588323  2.195513  0.597884  0.681385 -1.142265   
C       0.109641  1.226361  0.126650  0.037204  0.018875  0.839429  0.065700   

first             
second       two  
A      -1.496545  
B      -0.845397  
C      -2.422335

复利，就是复合利息，它是指每年的收益还可以产生收益，就是俗称的利滚利。复利的计算是对本金及其产生的利息一并计算，也就是利上有利。复利计算的特点是：把上期未的本利和作为下一期的本金，在计算时每一期本金的数额是不同的。
复利的计算公式：
复利的计算公式是：S＝P（1＋i）^n
即：本利之和＝本金×（1＋利率)×期数”这个“期数”时间因子是整个公式的关键因素，一年又一年(或一月一月)地相乘下来，数值当然会愈来愈大。
复合增长率是一项投资在特定时期内的年度增长率
计算方法为总增长率百分比的n方根，n相等于有关时期内的年数
公式为：(现有价值/基础价值)^(1/年数) - 1

In [ ]:
import numpy as np
import pandas as pd
import math

a = np.arange(1, 10)
f = 1
l = [f]
for i in range(5):
    f *= 1.1
    l.append(f)

s = pd.Series(l)
# print(s)

print(1 + s.pct_change())
print("prod:{}".format((1 + s.pct_change()).prod()))
print(1.1 ** 5)
print(s.shape[0])
print(1 / s.shape[0])
print((1 + s.pct_change()).prod() ** (1 / s.shape[0]) - 1)
print("average return:{}".format(math.pow((1 + s.pct_change()).prod(), 1/s.shape[0]) - 1))
print((1 + 0.08266451888074355) ** 6)
print("cumprod:{}".format((1 + s.pct_change()).cumprod()))


1、如果单利计算，10年：
10000*（1+10%*10）=20000
期限=(本利和/本金-1)/利率
=(20000/10000-1)/10%
=10
2、如果复利计算，约8年（7年多）：
本金*(1+10%)^期限=本利和
期限=LOG(本利和/本金，1+10%)
=LOG(20000/10000，1.1)
=LOG(2，1.1)
=7.27254

In [28]:
import math
print("复利:{}".format(0.71 ** ( 1 / 10) -1))
print((1 + 0.0795526) ** 10)

print((1 + 0.1) ** 36.362704486708566 )

print(math.log(32, 1.1))

复利:-0.03366917155991489
2.149998104428406
32.00000000000001
36.362704486708566


In [34]:
(-0.282863 -1.509059)/2

(189+258)*0.7

print(250/20)

12.5
